---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-semaphore-tester
    docker_networks:
      - name: 'test-ag-semaphore'
        ipam_config:
          - subnet: '192.168.15.0/24'
            gateway: '192.168.15.254'
    networks:
      - name: 'test-ag-semaphore'
        ipv4_address: '192.168.15.1'
    groups: [grp_tester]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true

  - name: test-ag-semaphore-1
    networks:
      - name: 'test-ag-semaphore'
        ipv4_address: '192.168.15.2'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: '/tmp'
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
